### ISSUE TITLE
General hints

### ISSUE THREAD

**Issue by surfmuggle** [PhiMo17/LZK#5]
The following remarks are recommendations or things i would do differently.

- [x] A method name should match what it does. How would you rename  	[`public void returnBill() `](https://github.com/PhiMo17/LZK/blob/4058d71d4aee2f47edcb5024afbcf1429398a0b0/KassenbonOO/src/ShoppingCart.java#L32) and also [`restock`](https://github.com/PhiMo17/LZK/blob/4058d71d4aee2f47edcb5024afbcf1429398a0b0/KassenbonOO/src/Article.java#L48)?
- [x] It may be better to extract [sum total for all items in the cart](https://github.com/PhiMo17/LZK/blob/4058d71d4aee2f47edcb5024afbcf1429398a0b0/KassenbonOO/src/ShoppingCart.java#L19) in its own method (lines 19 till 25) and possibly the discount as well
- [x] avoid [magic numbers](https://github.com/PhiMo17/LZK/blob/4058d71d4aee2f47edcb5024afbcf1429398a0b0/KassenbonOO/src/CartItem.java#L14)
- [x] Single level of abstraction [getItems](https://github.com/PhiMo17/LZK/blob/4058d71d4aee2f47edcb5024afbcf1429398a0b0/KassenbonOO/src/Main.java#L21) and [`parseInput`](https://github.com/PhiMo17/LZK/blob/4058d71d4aee2f47edcb5024afbcf1429398a0b0/KassenbonOO/src/Main.java#L30)

**Comment by PhiMo17** [comment]
I've commited todays changes to the test branch.
