### ISSUE TITLE
LZK - Refactor to use commandline only

### ISSUE THREAD

**Issue by surfmuggle** [PhiMo17/LZK#6]
Currently the LZK OO-Version runs with JFrame and with the command line. 

Rewrite it, so that it only uses the command line.

 - [x] Change code to run on the command line only
 - [x] What do you need to change to handle it if a user clicks cancel or wants to stop to enter products?
 - [x] improve single level of abstraction (SLA) see [this comment in Main](https://github.com/PhiMo17/LZK/commit/4058d71d4aee2f47edcb5024afbcf1429398a0b0#r50401036). This [article on SLA](https://www.c-sharpcorner.com/article/clean-code-single-level-of-abstraction/) may be of use

**Comment by surfmuggle** [comment]
Currently a user hast to enter a quantity for all articles. 

Expected: a user can go to checkout at any time
Actual: a user has to go through all articles `JOptionPane.showInputDialog()`. If the user clicks cancel an exception is thrown:


```
Exception in thread "main" java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:620)
        at java.base/java.lang.Integer.parseInt(Integer.java:776)
        at Main.main(Main.java:31)

```

**Comment by PhiMo17** [comment]
Commited to the test branch and did a pull-request
